name: Pitest
markdown: kramdown 
excerpt_separator: <!-- more -->
description: Pitest
url: http://pitest.org
relative_permalinks: false
permalink: /posts/:year/:month/:day/:title/
exclude: [README.md, .idea]
plugins:
  - jekyll-toc
